### ISSUE TITLE
Percy anywhere doesn't seem to work with RSpec

### ISSUE THREAD

**Issue by joscha** [percy/example-percy-anywhere#2]
When using `bundle exec rspec` as in the readme, Percy runs just fine w/o errors, but doesn't upload anything. Removing rspec fixes it. Example, see https://github.com/joscha/example-percy-react-storybook

references https://github.com/joscha/example-percy-react-storybook/issues/2

**Comment by fotinakis** [comment]
Whoops that's supposed to be `bundle exec ruby snapshots.rb` — fixing now.

**Comment by joscha** [comment]
@fotinakis This would only "fix" this example of using percy anywhere though (by not using rspec) - the issue still remains, Percy Anywhere and RSpec don't seem to work together - if you check out  https://github.com/joscha/example-percy-react-storybook/ you can see it failing.
